import path from 'path'
import { fileURLToPath } from 'url'
import Database from 'better-sqlite3'
import { classifyJob } from '../services/classifier.js'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const DB_PATH = path.join(__dirname, 'jobs.db')

const now = new Date()
function daysAgo(n) {
  const d = new Date(now); d.setDate(d.getDate() - n); return d.toISOString()
}

const JOBS = [
  // ── Original 8 sectors ───────────────────────────────────────────────────
  {
    id: 'seed_1',
    title: 'Investment Banking Analyst — Graduate',
    company: 'Goldman Sachs',
    location: 'London, UK',
    sector: 'Investment Banking',
    salary_min: 70000, salary_max: 85000, salary_currency: 'GBP',
    description: 'Two-year analyst program in our London IBD division. Work on M&A advisory, ECM, and DCM transactions across EMEA.',
    url: 'https://www.goldmansachs.com/careers',
    date_posted: daysAgo(1),
    deadline_type: 'date', deadline_date: '2026-09-30',
  },
  {
    id: 'seed_2',
    title: 'Asset Management Graduate Programme',
    company: 'BlackRock',
    location: 'London, UK',
    sector: 'Asset Management',
    salary_min: 60000, salary_max: 70000, salary_currency: 'GBP',
    description: 'Rotational graduate programme across iShares, Multi-Asset Strategies, and Fundamental Active Equity teams.',
    url: 'https://careers.blackrock.com',
    date_posted: daysAgo(2),
    deadline_type: 'rolling', deadline_date: null,
  },
  {
    id: 'seed_3',
    title: 'M&A Analyst — Entry Level',
    company: 'Morgan Stanley',
    location: 'Madrid, Spain',
    sector: 'M&A',
    salary_min: 55000, salary_max: 65000, salary_currency: 'EUR',
    description: 'Join our Madrid M&A team advising on cross-border transactions in the Iberian market and broader EMEA region.',
    url: 'https://www.morganstanley.com/careers',
    date_posted: daysAgo(3),
    deadline_type: 'date', deadline_date: '2026-08-15',
  },
  {
    id: 'seed_4',
    title: 'Wealth Management Associate',
    company: 'UBS',
    location: 'Milan, Italy',
    sector: 'Wealth Management',
    salary_min: 45000, salary_max: 60000, salary_currency: 'EUR',
    description: 'Support senior private bankers in managing portfolios for UHNW clients across Italy and the Mediterranean region.',
    url: 'https://www.ubs.com/careers',
    date_posted: daysAgo(5),
    deadline_type: null, deadline_date: null,
  },
  {
    id: 'seed_5',
    title: 'Private Equity Analyst',
    company: 'KKR',
    location: 'New York, US',
    sector: 'Private Equity',
    salary_min: 120000, salary_max: 150000, salary_currency: 'USD',
    description: 'Analyst position on our Americas PE team. Source and execute LBO investments across technology, healthcare, and industrials.',
    url: 'https://www.kkr.com/careers',
    date_posted: daysAgo(6),
    deadline_type: 'date', deadline_date: '2026-07-31',
  },
  {
    id: 'seed_6',
    title: 'Venture Capital Analyst',
    company: 'Sequoia Capital',
    location: 'New York, US',
    sector: 'Venture Capital',
    salary_min: 100000, salary_max: 130000, salary_currency: 'USD',
    description: 'Early-stage VC analyst role. Source Series A and B opportunities, conduct due diligence, and support portfolio companies.',
    url: 'https://www.sequoiacap.com',
    date_posted: daysAgo(7),
    deadline_type: 'rolling', deadline_date: null,
  },
  {
    id: 'seed_7',
    title: 'Financial Analyst — Graduate Scheme',
    company: 'ING Group',
    location: 'Amsterdam, Netherlands',
    sector: 'Commercial Banking',
    salary_min: 42000, salary_max: 52000, salary_currency: 'EUR',
    description: '18-month graduate rotation across corporate finance, risk, and structured products in our Amsterdam HQ.',
    url: 'https://www.ing.jobs',
    date_posted: daysAgo(8),
    deadline_type: null, deadline_date: null,
  },
  {
    id: 'seed_8',
    title: 'Private Banking Graduate',
    company: 'Santander',
    location: 'Madrid, Spain',
    sector: 'Private Banking',
    salary_min: 38000, salary_max: 48000, salary_currency: 'EUR',
    description: 'Graduate training programme in Santander Private Banking Madrid. Client-facing role from day one.',
    url: 'https://www.santander.com/careers',
    date_posted: daysAgo(10),
    deadline_type: 'date', deadline_date: '2026-10-01',
  },
  {
    id: 'seed_9',
    title: 'Equity Research Analyst',
    company: 'JPMorgan',
    location: 'London, UK',
    sector: 'Equity Research',
    salary_min: 65000, salary_max: 80000, salary_currency: 'GBP',
    description: 'Analyst role in our London Equity Research division covering European financials and real estate.',
    url: 'https://jpmorgan.com/careers',
    date_posted: daysAgo(12),
    deadline_type: 'rolling', deadline_date: null,
  },
  {
    id: 'seed_10',
    title: 'Investment Analyst — Fixed Income',
    company: 'PIMCO',
    location: 'Amsterdam, Netherlands',
    sector: 'Asset Management',
    salary_min: 55000, salary_max: 68000, salary_currency: 'EUR',
    description: 'Fixed income investment analyst supporting portfolio managers on European credit and rates strategies.',
    url: 'https://pimco.com/careers',
    date_posted: daysAgo(14),
    deadline_type: null, deadline_date: null,
  },
  // ── Sales & Trading ───────────────────────────────────────────────────────
  {
    id: 'seed_11',
    title: 'Sales & Trading Analyst',
    company: 'Barclays',
    location: 'London, UK',
    sector: 'Sales & Trading',
    salary_min: 65000, salary_max: 80000, salary_currency: 'GBP',
    description: 'Graduate analyst in our Markets division. Rotations across fixed income, equities, FX, and commodities desks.',
    url: 'https://www.barclays.com/careers',
    date_posted: daysAgo(2),
    deadline_type: 'date', deadline_date: '2026-11-01',
  },
  {
    id: 'seed_12',
    title: 'Equities Sales & Trading Graduate',
    company: 'Citigroup',
    location: 'New York, US',
    sector: 'Sales & Trading',
    salary_min: 110000, salary_max: 140000, salary_currency: 'USD',
    description: 'Two-year analyst programme across S&T desks in NYC. Exposure to institutional client coverage and market-making.',
    url: 'https://careers.citi.com',
    date_posted: daysAgo(4),
    deadline_type: 'rolling', deadline_date: null,
  },
  // ── Brokerage & Market Making ─────────────────────────────────────────────
  {
    id: 'seed_13',
    title: 'Junior Market Maker — Equities',
    company: 'Virtu Financial',
    location: 'New York, US',
    sector: 'Brokerage & Market Making',
    salary_min: 95000, salary_max: 130000, salary_currency: 'USD',
    description: 'Entry-level market making on our equities desk. Work with proprietary algorithms and real-time execution systems.',
    url: 'https://www.virtu.com/careers',
    date_posted: daysAgo(3),
    deadline_type: 'rolling', deadline_date: null,
  },
  {
    id: 'seed_14',
    title: 'Graduate Trader — ETF & Derivatives',
    company: 'IMC Trading',
    location: 'Amsterdam, Netherlands',
    sector: 'Brokerage & Market Making',
    salary_min: 55000, salary_max: 70000, salary_currency: 'EUR',
    description: "Full training in derivatives and ETF market making at one of Europe's leading proprietary trading firms.",
    url: 'https://www.imc.com/careers',
    date_posted: daysAgo(6),
    deadline_type: null, deadline_date: null,
  },
  // ── Equity Research ───────────────────────────────────────────────────────
  {
    id: 'seed_15',
    title: 'Research Associate — European Equities',
    company: 'Deutsche Bank',
    location: 'London, UK',
    sector: 'Equity Research',
    salary_min: 60000, salary_max: 75000, salary_currency: 'GBP',
    description: 'Support senior analysts covering FTSE and DAX-listed companies. Produce sector reports and financial models.',
    url: 'https://www.db.com/careers',
    date_posted: daysAgo(4),
    deadline_type: 'date', deadline_date: '2026-09-15',
  },
  {
    id: 'seed_16',
    title: 'Equity Research Analyst — Banks',
    company: 'BNP Paribas',
    location: 'London, UK',
    sector: 'Equity Research',
    salary_min: 58000, salary_max: 72000, salary_currency: 'GBP',
    description: 'Cover European banking sector for institutional clients. Build valuation models and write client-facing research notes.',
    url: 'https://bnpparibas.com/careers',
    date_posted: daysAgo(9),
    deadline_type: 'rolling', deadline_date: null,
  },
  // ── Risk Management ───────────────────────────────────────────────────────
  {
    id: 'seed_17',
    title: 'Market Risk Analyst — Graduate',
    company: 'HSBC',
    location: 'London, UK',
    sector: 'Risk Management',
    salary_min: 52000, salary_max: 65000, salary_currency: 'GBP',
    description: 'Monitor market risk across trading portfolios using VaR models, stress testing, and regulatory reporting frameworks.',
    url: 'https://www.hsbc.com/careers',
    date_posted: daysAgo(5),
    deadline_type: 'date', deadline_date: '2026-10-15',
  },
  {
    id: 'seed_18',
    title: 'Credit Risk Analyst',
    company: 'Société Générale',
    location: 'Milan, Italy',
    sector: 'Risk Management',
    salary_min: 40000, salary_max: 52000, salary_currency: 'EUR',
    description: 'Assess credit risk for corporate clients in the Italian and Southern European market. Graduate entry role.',
    url: 'https://careers.societegenerale.com',
    date_posted: daysAgo(11),
    deadline_type: null, deadline_date: null,
  },
  // ── Quantitative Analysis ─────────────────────────────────────────────────
  {
    id: 'seed_19',
    title: 'Quantitative Analyst — Entry Level',
    company: 'Two Sigma',
    location: 'New York, US',
    sector: 'Quantitative Analysis',
    salary_min: 130000, salary_max: 180000, salary_currency: 'USD',
    description: 'Apply statistical and ML techniques to financial data. Build and validate systematic trading strategy models.',
    url: 'https://www.twosigma.com/careers',
    date_posted: daysAgo(3),
    deadline_type: 'date', deadline_date: '2026-12-01',
  },
  {
    id: 'seed_20',
    title: 'Quant Researcher Graduate',
    company: 'AQR Capital',
    location: 'New York, US',
    sector: 'Quantitative Analysis',
    salary_min: 120000, salary_max: 160000, salary_currency: 'USD',
    description: 'Research systematic investment strategies. Strong quantitative background required — Stats, Maths, Physics, or CS.',
    url: 'https://www.aqr.com/careers',
    date_posted: daysAgo(7),
    deadline_type: 'rolling', deadline_date: null,
  },
  // ── Financial Advisory ────────────────────────────────────────────────────
  {
    id: 'seed_21',
    title: 'Financial Advisory Analyst',
    company: 'Lazard',
    location: 'London, UK',
    sector: 'Financial Advisory',
    salary_min: 65000, salary_max: 78000, salary_currency: 'GBP',
    description: 'Work on M&A advisory, restructuring, and capital markets transactions for sovereign and corporate clients worldwide.',
    url: 'https://www.lazard.com/careers',
    date_posted: daysAgo(2),
    deadline_type: 'date', deadline_date: '2026-08-31',
  },
  {
    id: 'seed_22',
    title: 'Advisory Graduate Programme',
    company: 'Rothschild & Co',
    location: 'Madrid, Spain',
    sector: 'Financial Advisory',
    salary_min: 42000, salary_max: 55000, salary_currency: 'EUR',
    description: 'Two-year rotation across M&A advisory and capital markets. Work on landmark European cross-border transactions.',
    url: 'https://www.rothschildandco.com/careers',
    date_posted: daysAgo(8),
    deadline_type: 'rolling', deadline_date: null,
  },
  // ── Corporate Finance ─────────────────────────────────────────────────────
  {
    id: 'seed_23',
    title: 'Corporate Finance Analyst',
    company: 'Shell',
    location: 'Amsterdam, Netherlands',
    sector: 'Corporate Finance',
    salary_min: 50000, salary_max: 62000, salary_currency: 'EUR',
    description: 'Support M&A and investment appraisal for major energy transition projects. Global capital allocation exposure.',
    url: 'https://careers.shell.com',
    date_posted: daysAgo(6),
    deadline_type: 'rolling', deadline_date: null,
  },
  {
    id: 'seed_24',
    title: 'Graduate — Corporate Finance',
    company: 'KPMG',
    location: 'London, UK',
    sector: 'Corporate Finance',
    salary_min: 48000, salary_max: 58000, salary_currency: 'GBP',
    description: 'Financial due diligence and valuation work on transactions across TMT, consumer, and infrastructure sectors.',
    url: 'https://home.kpmg/careers',
    date_posted: daysAgo(13),
    deadline_type: 'date', deadline_date: '2026-09-05',
  },
  // ── Treasury ──────────────────────────────────────────────────────────────
  {
    id: 'seed_25',
    title: 'Treasury Analyst — Graduate',
    company: 'Unilever',
    location: 'London, UK',
    sector: 'Treasury',
    salary_min: 42000, salary_max: 52000, salary_currency: 'GBP',
    description: "Manage liquidity, FX hedging, and debt financing for one of the world's largest consumer goods companies.",
    url: 'https://careers.unilever.com',
    date_posted: daysAgo(4),
    deadline_type: 'date', deadline_date: '2026-11-15',
  },
  {
    id: 'seed_26',
    title: 'Group Treasury Trainee',
    company: 'Philips',
    location: 'Amsterdam, Netherlands',
    sector: 'Treasury',
    salary_min: 38000, salary_max: 48000, salary_currency: 'EUR',
    description: 'Trainee role within the Philips Group Treasury team. Cash management, FX, and interest rate risk exposure.',
    url: 'https://www.philips.com/careers',
    date_posted: daysAgo(10),
    deadline_type: null, deadline_date: null,
  },
  // ── Compliance & Regulatory ───────────────────────────────────────────────
  {
    id: 'seed_27',
    title: 'Compliance Analyst — Graduate',
    company: 'BBVA',
    location: 'Madrid, Spain',
    sector: 'Compliance & Regulatory',
    salary_min: 36000, salary_max: 45000, salary_currency: 'EUR',
    description: "Support regulatory compliance across BBVA's EMEA operations. AML, MiFID II, and conduct risk frameworks.",
    url: 'https://careers.bbva.com',
    date_posted: daysAgo(5),
    deadline_type: 'rolling', deadline_date: null,
  },
  {
    id: 'seed_28',
    title: 'Regulatory Affairs Analyst',
    company: 'Nomura',
    location: 'London, UK',
    sector: 'Compliance & Regulatory',
    salary_min: 55000, salary_max: 68000, salary_currency: 'GBP',
    description: "Ensure compliance with FCA and PRA regulations across Nomura's European banking operations.",
    url: 'https://www.nomura.com/careers',
    date_posted: daysAgo(15),
    deadline_type: 'date', deadline_date: '2026-10-31',
  },
  // ── Financial Technology (FinTech) ────────────────────────────────────────
  {
    id: 'seed_29',
    title: 'FinTech Analyst — Finance Graduate',
    company: 'Revolut',
    location: 'London, UK',
    sector: 'Financial Technology (FinTech)',
    salary_min: 55000, salary_max: 70000, salary_currency: 'GBP',
    description: 'Work at the intersection of finance and technology — product analytics, financial modelling, and growth initiatives.',
    url: 'https://www.revolut.com/careers',
    date_posted: daysAgo(3),
    deadline_type: 'date', deadline_date: '2026-12-15',
  },
  {
    id: 'seed_30',
    title: 'Finance & Strategy Analyst',
    company: 'N26',
    location: 'Amsterdam, Netherlands',
    sector: 'Financial Technology (FinTech)',
    salary_min: 45000, salary_max: 58000, salary_currency: 'EUR',
    description: "Financial planning and strategic analysis at one of Europe's fastest-growing neobanks.",
    url: 'https://n26.com/careers',
    date_posted: daysAgo(9),
    deadline_type: 'rolling', deadline_date: null,
  },
]

const GENERAL_BUSINESS_JOBS = [
  {
    id: 'seed_31',
    title: 'Graduate Business Analyst',
    company: 'Deloitte',
    location: 'London, UK',
    sector: 'Business Analysis',
    salary_min: 36000, salary_max: 44000, salary_currency: 'GBP',
    description: 'Graduate role helping clients map processes, gather requirements, and turn business problems into practical delivery plans.',
    url: 'https://www.deloitte.com/careers',
    date_posted: daysAgo(1),
    deadline_type: 'date', deadline_date: '2026-10-20',
  },
  {
    id: 'seed_32',
    title: 'Junior Strategy Consultant',
    company: 'Accenture',
    location: 'Madrid, Spain',
    sector: 'Strategy & Consulting',
    salary_min: 34000, salary_max: 43000, salary_currency: 'EUR',
    description: 'Entry-level consulting role across growth strategy, digital transformation, operating model design, and client workshops.',
    url: 'https://www.accenture.com/careers',
    date_posted: daysAgo(2),
    deadline_type: 'rolling', deadline_date: null,
  },
  {
    id: 'seed_33',
    title: 'Operations Graduate Programme',
    company: 'Amazon',
    location: 'Milan, Italy',
    sector: 'Operations',
    salary_min: 36000, salary_max: 46000, salary_currency: 'EUR',
    description: 'Rotational operations programme focused on process improvement, team planning, service metrics, and supply chain execution.',
    url: 'https://www.amazon.jobs',
    date_posted: daysAgo(2),
    deadline_type: 'date', deadline_date: '2026-09-25',
  },
  {
    id: 'seed_34',
    title: 'Marketing Coordinator - Graduate',
    company: "L'Oreal",
    location: 'Paris, France',
    sector: 'Marketing',
    salary_min: 35000, salary_max: 44000, salary_currency: 'EUR',
    description: 'Support campaign planning, brand reporting, social activations, and launch coordination across European consumer markets.',
    url: 'https://careers.loreal.com',
    date_posted: daysAgo(3),
    deadline_type: 'rolling', deadline_date: null,
  },
  {
    id: 'seed_35',
    title: 'Associate Product Manager - Early Career',
    company: 'Booking.com',
    location: 'Amsterdam, Netherlands',
    sector: 'Product Management',
    salary_min: 48000, salary_max: 62000, salary_currency: 'EUR',
    description: 'Work with design, engineering, data, and commercial teams to improve customer journeys and prioritize product experiments.',
    url: 'https://careers.booking.com',
    date_posted: daysAgo(4),
    deadline_type: null, deadline_date: null,
  },
  {
    id: 'seed_36',
    title: 'Business Development Representative',
    company: 'Salesforce',
    location: 'Dublin, Ireland',
    sector: 'Sales & Business Development',
    salary_min: 42000, salary_max: 56000, salary_currency: 'EUR',
    description: 'Early-career commercial role building pipeline, qualifying customer needs, and partnering with account executives.',
    url: 'https://www.salesforce.com/company/careers',
    date_posted: daysAgo(4),
    deadline_type: 'rolling', deadline_date: null,
  },
  {
    id: 'seed_37',
    title: 'Supply Chain Analyst Graduate',
    company: 'Procter & Gamble',
    location: 'London, UK',
    sector: 'Supply Chain',
    salary_min: 39000, salary_max: 50000, salary_currency: 'GBP',
    description: 'Analyse demand, inventory, supplier performance, and logistics trade-offs for consumer goods supply networks.',
    url: 'https://www.pgcareers.com',
    date_posted: daysAgo(5),
    deadline_type: 'date', deadline_date: '2026-11-10',
  },
  {
    id: 'seed_38',
    title: 'People Operations Associate',
    company: 'Spotify',
    location: 'Stockholm, Sweden',
    sector: 'Human Resources',
    salary_min: 38000, salary_max: 48000, salary_currency: 'EUR',
    description: 'Support onboarding, employee lifecycle processes, HR reporting, and people operations projects for early-career talent.',
    url: 'https://www.lifeatspotify.com/jobs',
    date_posted: daysAgo(6),
    deadline_type: null, deadline_date: null,
  },
  {
    id: 'seed_39',
    title: 'Project Coordinator - Graduate',
    company: 'Siemens',
    location: 'Munich, Germany',
    sector: 'Project Management',
    salary_min: 42000, salary_max: 54000, salary_currency: 'EUR',
    description: 'Coordinate milestones, stakeholders, risks, and documentation for industrial technology and transformation projects.',
    url: 'https://jobs.siemens.com',
    date_posted: daysAgo(6),
    deadline_type: 'rolling', deadline_date: null,
  },
  {
    id: 'seed_40',
    title: 'Data Analyst - Commercial Insights',
    company: 'Heineken',
    location: 'Amsterdam, Netherlands',
    sector: 'Data & Analytics',
    salary_min: 42000, salary_max: 54000, salary_currency: 'EUR',
    description: 'Turn sales, pricing, and customer data into clear recommendations for commercial and marketing teams.',
    url: 'https://careers.theheinekencompany.com',
    date_posted: daysAgo(7),
    deadline_type: 'date', deadline_date: '2026-10-05',
  },
  {
    id: 'seed_41',
    title: 'Customer Success Associate',
    company: 'HubSpot',
    location: 'Berlin, Germany',
    sector: 'Customer Success',
    salary_min: 40000, salary_max: 52000, salary_currency: 'EUR',
    description: 'Help customers adopt software, track account health, and coordinate practical next steps with sales and support teams.',
    url: 'https://www.hubspot.com/careers',
    date_posted: daysAgo(8),
    deadline_type: 'rolling', deadline_date: null,
  },
  {
    id: 'seed_42',
    title: 'Commercial Graduate Trainee',
    company: 'Nestle',
    location: 'Milan, Italy',
    sector: 'Sales & Business Development',
    salary_min: 33000, salary_max: 42000, salary_currency: 'EUR',
    description: 'Rotational commercial programme across category management, key account support, pricing, and channel strategy.',
    url: 'https://www.nestle.com/jobs',
    date_posted: daysAgo(9),
    deadline_type: 'date', deadline_date: '2026-09-18',
  },
  {
    id: 'seed_43',
    title: 'Procurement Analyst - Entry Level',
    company: 'Maersk',
    location: 'Copenhagen, Denmark',
    sector: 'Supply Chain',
    salary_min: 43000, salary_max: 55000, salary_currency: 'EUR',
    description: 'Support sourcing, supplier analysis, contract preparation, and procurement reporting for logistics operations.',
    url: 'https://www.maersk.com/careers',
    date_posted: daysAgo(9),
    deadline_type: null, deadline_date: null,
  },
  {
    id: 'seed_44',
    title: 'Graduate Management Consultant',
    company: 'KPMG',
    location: 'London, UK',
    sector: 'Strategy & Consulting',
    salary_min: 37000, salary_max: 46000, salary_currency: 'GBP',
    description: 'Support client research, operating model analysis, workshop preparation, and implementation planning.',
    url: 'https://home.kpmg/careers',
    date_posted: daysAgo(10),
    deadline_type: 'rolling', deadline_date: null,
  },
  {
    id: 'seed_45',
    title: 'Junior CRM Marketing Specialist',
    company: 'Zalando',
    location: 'Berlin, Germany',
    sector: 'Marketing',
    salary_min: 38000, salary_max: 50000, salary_currency: 'EUR',
    description: 'Coordinate lifecycle campaigns, customer segments, testing plans, and performance reporting for CRM channels.',
    url: 'https://jobs.zalando.com',
    date_posted: daysAgo(11),
    deadline_type: null, deadline_date: null,
  },
  {
    id: 'seed_46',
    title: 'Business Operations Analyst',
    company: 'Wise',
    location: 'London, UK',
    sector: 'Operations',
    salary_min: 45000, salary_max: 58000, salary_currency: 'GBP',
    description: 'Analyse operational performance, improve service workflows, and partner with product and compliance teams.',
    url: 'https://wise.jobs',
    date_posted: daysAgo(12),
    deadline_type: 'rolling', deadline_date: null,
  },
]

const ALL_JOBS = [...JOBS, ...GENERAL_BUSINESS_JOBS]

const INSERT_SQL = `
  INSERT OR REPLACE INTO jobs (
    id, title, company, company_logo, location, sector,
    salary_min, salary_max, salary_currency, description, url,
    date_posted, source, deadline_type, deadline_date,
    grand_category, sub_type
  ) VALUES (?, ?, ?, NULL, ?, ?, ?, ?, ?, ?, ?, ?, 'seed', ?, ?, ?, ?)
`

// Called by index.js as an API-failure fallback (uses the shared db connection)
export function seedDb(db) {
  const stmt = db.prepare(INSERT_SQL)
  for (const job of ALL_JOBS) {
    const { grandCategory, subType } = classifyJob(job.title)
    stmt.run(
      job.id, job.title, job.company,
      job.location, job.sector,
      job.salary_min, job.salary_max, job.salary_currency,
      job.description, job.url, job.date_posted,
      job.deadline_type ?? null, job.deadline_date ?? null,
      grandCategory, subType,
    )
  }
  return ALL_JOBS.length
}

// Direct execution: node server/db/seed.js
const isMain = process.argv[1]?.endsWith('seed.js')
if (isMain) {
  const db = new Database(DB_PATH)
  db.exec(`
    CREATE TABLE IF NOT EXISTS jobs (
      id TEXT PRIMARY KEY, title TEXT NOT NULL, company TEXT NOT NULL,
      company_logo TEXT, location TEXT, sector TEXT,
      salary_min REAL, salary_max REAL, salary_currency TEXT,
      description TEXT, url TEXT NOT NULL, date_posted TEXT,
      source TEXT DEFAULT 'seed', created_at TEXT DEFAULT (datetime('now')),
      expires_at TEXT, deadline_type TEXT, deadline_date TEXT,
      grand_category TEXT, sub_type TEXT
    )
  `)
  const n = seedDb(db)
  console.log(`✓ Seeded ${n} jobs into ${DB_PATH}`)
  db.close()
}
